### ISSUE TITLE
Remove sqlalchemy dependency?

### ISSUE THREAD

**Issue by ckcollab** [robrua/cassiopeia#24]
Heyoo! First of all, thanks so much for all the hard work on this, definitely stands above the rest of the Riot python APIs :)

Do you think it would make sense to remove the requirement to install sqlalchemy along with this? I believe it's not required? I wouldn't mind doing the work myself, just wondering if that's kosher!

**Comment by robrua** [comment]
I haven't really decided where I stand on this. On the one hand, the codebase already runs w/o sqlalchemy installed. On the other, part of the goal of Cass is making everything easy for new users, and part of that is trying to make sure people don't hit a missing dependency trying to use a feature. 

My outlook so far has been that most advanced users are going to be running Cass from a clone of the git repo instead of installing from pip, so they won't have sqlalchemy installed automatically. Even if they did, sqlalchemy is barely noticeable @ 4MB and can be removed if it's a concern.

Let me know your thoughts on this. For now I'm tempted to say leave it as a requirement.

**Comment by ckcollab** [comment]
> most advanced users are going to be running Cass from a clone of the git repo

Really? I don't know anyone who does that, unless they're developing with it? Much nicer to manage dependencies with `pip` and `requirements.txt` imo.

It's not a huge deal, just kind of annoying to have an extra dependency, I feel like most people using SQLAlchemy would know what's up. Just my opinion!

**Comment by robrua** [comment]
Since bugfixes and API changes are so common, most of the people I help out w/Cass a lot seem to be using the latest version off github. I usually don't make a new release until I feel like there's been enough small changes or a big enough single change.

You may be right that it's pretty clear you're using a new dependency when you start working w/the SQLAlchemy stuff. I'll ask around some people I know use it.

**Comment by ckcollab** [comment]
:+1:

**Comment by robrua** [comment]
So for now I'm thinking we'll stick with this, since pretty much everyone I talked to didn't even know that sqlalchemy got installed, and didn't care whether it was. They just wanted the lib to work as advertised on the box.

**Comment by ckcollab** [comment]
S'all good!

**Comment by MakersF** [comment]
Just to leave a feed back, as I was the one that initially proposed to make the sqlalchemy imports conditionals (and thus allow to use the library without SQLAlchemy).

The good(tm) solution is to split the library into the DTO project and the Cassiopeia project.
Cassiopeia will have DTO as dependency and SQLAlchemy in the requirements, while DTO will not.

To the users of cassiopeia (from pip) this won't make a single difference, they would probably not even notice the change (as when they upgrade with pip they get the DTO library), and whoever doeesn't want SQLAlchemy can use the DTO library.

Personally I use only the DTO part of the library, but I don't care at the moment having SQLAlchemy in the requirements as the code I'm using in production requires that anyways.

I must admit that I see cassiopeia as a basis for many libraries (basically any library written in python, as it's a easy and tested interface over the plain riot API) and thus I'd be supportive of scrapping SQLAlchemy for the unneeded part, as this would force any library building on cassioepia to have SQLalchemy in the requirements.

But this is not the ideal world, I don't believe the cost/benefit of such a change would be enough to warrant it
