### ISSUE TITLE
Allow to use the DTOs without SQLAlchemy

### ISSUE THREAD

**Issue by MakersF** [robrua/cassiopeia#4]
How do you feel about splitting the DTOs from the SQLAlchemy?
I mean, having the DTOs without importing SQLALchemy and have the SQLAlchemy bindings in separate files.

I'm starting a project now, and would like to use your DTOs in order not to redo all the work you already done to extract the informations in a simple way.
I only need the parsing though, as I'll gather the data in a different way and I'm not interested in the additional features of your library.

Taking for example match.py, we could have

dto/match.py
dto/alchemy/match_alchemy.py

match.py would contain line 5-594
match_alchemy.py would contain
line 1-5
from cassiopeia.type.dto.match import *
line 594-926

This way whoever needs to have the data parsing can use your library without pulling external dependencies and using pure python.

If you believe this can be useful I might make a pull request for the changes I'll do for my project

**Comment by robrua** [comment]
As it stands the SQLAlchemy bindings aren't applied until you specify to use an SQLAlchemyDB as the datastore. In that sense, the Dtos are already split from the bindings. The only thing that should be tripping you up if you don't have SQLAlchemy installed is the imports themselves.

My problem with this proposed approach is that it hurts interopability of data stores - at best there'd have to be logic in baseriotapi to return the proper type of dto according to which data store type is being used.

I think the same effect (allowing operation w/o SQLAlchemy installed) can be achieved simply by switching the sqlalchemy imports to be conditional on it being installed. I'll take a closer look at this later today.

**Comment by MakersF** [comment]
I agree with you!
With the last pull request I just moved the pure python part in its own file, and the change is completely transparent to the users of the file.
Eg: whoever was using dto.match before will continue to use it as before, and in addition there is dto.pure.match which provides the python part without SQLAlchemy.

I agree with you that having conditional imports will probably be better, but I guess that it will still trigger "errors" in IDEs, kind of annoying.

For what concerns me, I'm fine having just the DTOs, without the Core functionality.
With the last commit, the pull request shouldn't change the library functionality, but just the layout of code.

Do you mind checking it?

**Comment by robrua** [comment]
I've been thinking about this and I really feel like conditional imports are the "right" solution to this problem. I'm really hesitant to complicate the type package structure, as it adds ambiguity as to what you're supposed to use (I already get questions about whether to use DTO or Core).

Is there something besides IDE errors that you think would be a problem w/the conditional import approach?

**Comment by MakersF** [comment]
Thought about it, and I made the imports conditional.
See https://github.com/robrua/cassiopeia/pull/6

**Comment by robrua** [comment]
1) I'm not sure why you say the bindings aren't currently an additional layer. The setup is currently designed to give you the "best of both worlds" as the bindings aren't applied unless they're an SQLAlchemyDB is being used. There's no SQLAlchemy involved if you don't set the datastore to use one.

There's already a system in place to let users add any type of storage they'd like - check out store.py/DataStore and riotapi.set_data_store.

2) This is entirely intentional. The guidelines of Riot API forbid you from using multiple API keys at once.

**Comment by MakersF** [comment]
Thanks for the merge!

I guess we have different opinions on architecture design.
I just don't see a reason why SQLAlchemy bindings should be first class citizens in the library, and if someone wanted to add another binding (for example MySQL) he would have to put them in their own file, and not in the dto.

Anyways, I'll make other pull request if I make some changes or additions which could be useful.

**Comment by robrua** [comment]
The reason for SQLAlchemy's level of inclusion is that I'm not interested in this library becoming a database toolkit the Riot API. There are already database toolkits that do a much better job than I could, so I'm using one instead of trying to reinvent the wheel.

SQLAlchemy has production ready support for Firebird, MS SQL, MySQL, Oracle, PostgreSQL, SQLite, Sybase, DB2, Redshift, EXASolution, SQL Anywhere, and MonetDB. New support is constantly under development.

I grant that someone might want to use something that isn't supported yet, but given that it'd be a massive undertaking custom-build a solution of comparable quality to SQLAlchemy support, I don't think there's going to be much interest in doing it, and I don't think it's a good idea to integrate lower quality solutions at the same level.
