### ISSUE TITLE
Difference between dto and core?

### ISSUE THREAD

**Issue by simoncos** [robrua/cassiopeia#50]
Hey guys, can you tell me the difference between dto and core in root directory and type directory? I'm trying to use cassiopeia but don't know which one I should call. 

Besides, I want to know how to obtain Event data in a Match?

Thank you.

**Comment by jjmaldonis** [comment]
Absolutely. The dto objects fit the Riot API specifications exactly, which means that we use the exact same names and datatypes in the dto layer as Riot does. Riot essentially returns dictionaries when you hit their service, and we process those dictionaries into python objects (so you can do `match.matchId` rather than `match['matchId']`.

A good example of the difference between the core and dto layer can be seen from how we implemented match.participants in each. In the dto layer, `match.participants` and `match.participantIdentities` return exactly what the Riot API returns. However, we feel like the information contained in those two objects should be part of the same object, so in the core layer we have wrapped them both up in the `match.participants` object (i.e. both `match.participants[0].name` (summoner name) and `match.participants[0].runes` are inside the same object).

In addition, in the core layer we have added extra functionality to some objects. For example, `match.participants["Dyrus"]` is valid in addition to `match.participants[0]`, which just makes it easy to access the participant you want on the first try (rather than having to loop through `match.participants` until you find a summoner with name "Dyrus").  Another example can be found in the recently added `riotapi.get_champion_masteries` function. The dto renders a list of Champion Mastery objects (one for each champion), because that's what Riot returns -- a list.  However, we think that you might just want to look up the champion mastery object for e.g. Annie, so in the core layer we made the list into a dictionary. Now you can do `riotapi.get_champion_masteries()[annie]` (where `annie` is a Champion object from `riotapi.get_champion_by_name("Annie")` and easily get just the champion mastery object for just Annie from the "list" of all champion masteries.  Finally, one of my favorite things about the core layer is being able to access a player's participant frame (within Match) via the participant object; in the dto layer, you have to lookup the participant ID first, then go through match.timeline.frames and look through a list for the participant's frame in each Frame object.

We think the core layer is best because it makes using the Riot API _much_ easier. The dto still helps a lot (e.g. automatic rate limiting), but it doesn't make working with the data itself any easier. I rarely ever use the dto layer myself, and I can legitimately only think of two one use-case when you might want to do so. The first is if you _really_ care about the speed of the application itself. This might sound big to you, but does it really matter if your code takes 12 second vs. 10 seconds or 120 milliseconds vs 100 milliseconds? Those 2 seconds (or 20 milliseconds) you potentially save running the code is almost always wayyyy less than the extra time it takes you to write the dto code (because it is much messier and less intuitive that the core code). On rare occasions, I will write core code while I write and test my code to make sure it is works correctly, and then once I know it works I will convert it to dto code to make it 10% faster.  However, if you really care about speed, you probably do not even want to use dto objects, but instead use the dictionaries sent straight from Riot. That would not be enjoyable at all though, and it gets rid of all the great things about Cass.

Let us know if you still have questions.

**Comment by sbrodehl** [comment]
You can access the ```Event``` data via the ```Match``` object, e.g.
```python
summoner = riotapi.get_summoner_by_name("dyrus")
match_id = riotapi.get_match_list(summoner, seasons=Season.season_5)[0].id
match = riotapi.get_match(match_id)
```
now you can access the timeline and the frames in ```match```, which hold the ```event``` data. Take a look at the [docs](http://cassiopeia.readthedocs.org/en/latest/cassiopeia.type.core.html?highlight=cassiopeia.type.core.match.match#cassiopeia.type.core.match.Match).

**Comment by jjmaldonis** [comment]
I just realized I did not answer your question correctly:

>can you tell me the difference between dto and core in root directory and type directory?

In Cass, there are two "layers", dto and core, which talked about above. However, the difference between the dto and core objects _in the root directory_ vs. _in the type directory_ is that in the root directory, the dto and core files contain api calls, whereas in the type directory, the dto and core files contain the actual objects that get rendered from those api calls. If you look in the files (and at the file names) closely, I think it will make sense.

And thank you @sbrodehl for answering the rest of the question as well. @simoncos once you have the `match`, you can access events by (for example) `match.timeline.frames[0].events`, which will give  you a list of `Event` objects.

**Comment by simoncos** [comment]
Dear @jjmaldonis , as for the first question, there was some ambiguity in my quesion. Your answer in the first reply is exactly what I want to know.

As for the second question, firstly thank you @jjmaldonis @sbrodehl for the answers. Actually my goal is to do some analysis about the match data. To be more specific, I want to know that in a certain match, which champion killed which champion for how many times, and which champion assisted in the events. This means I need all the Event data in matches. I've tried in the Riot's API, but found returned results like https://na.api.pvp.net/api/lol/na/v2.2/match/2069455529?includeTimeline=1&api_key=XXX didn't contain Event objects. 

I've tried the same thing in Cass following your posts, and found that the **events** list is null. Does this mean that not all matches have events data and thus I cannot reach my goal?

**Comment by robrua** [comment]
The includeTimeline parameter doesn't accept booleans specified as 0/1. You'll have to make a call to https://na.api.pvp.net/api/lol/na/v2.2/match/2069455529?includeTimeline=true&api_key=XXX instead to find that there are Event objects.

When I access this match with Cass, I find that the events list is properly filled in. One such event can be found using riotapi.get_match(2069455529).timeline[1][0].

You may find that some of the Match Frame objects don't contain any Events (particularly the first often does not), but you should be able to get the data you need searching over all the Frames' Event lists.

**Comment by sbrodehl** [comment]
One should note that not all matches have timeline data. If timeline data is requested, but doesn't exist, then the response won't include it.
I'm not sure what kind of games don't have timeline data, usually ranked games do.

**Comment by simoncos** [comment]
Thanks a lot guys!
